### ISSUE TITLE
Oracle Java 10 is out

### ISSUE THREAD

**Issue by robertdebock** [robertdebock/ansible-role-java#6]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Oracle has released [Java 10](http://www.oracle.com/technetwork/java/javase/downloads/index.html). Please modify the role to also allow Oracle Java 10. (jdk & jre)

**Comment by Eimert** [comment]
The sames goes for [OpenJDK 10](http://openjdk.java.net/projects/jdk/10/) ;)

**Comment by robertdebock** [comment]
Hi @Eimert, nice to see you here!

I did not realize that, good to know, thanks. When distributions release their new version, it may include openjdk 10. When openjdk 10 is available in a release, I'll update this role.

Debian (buster/sid) already has openjdk-10 available. That's really quick!

Oracle java 10 is being tested [now](https://travis-ci.org/robertdebock/ansible-role-java/builds/358253156).

**Comment by robertdebock** [comment]
It works, tested on CentOS 7 with java 10 from oracle, both tar.gz and rpm.
