### ISSUE TITLE
multiple JDKs

### ISSUE THREAD

**Issue by bbaassssiiee** [robertdebock/ansible-role-java#8]
**Is your feature request related to a problem? Please describe.**
I need to migrate to newer Java.

**Describe the solution you'd like**
I need java 8, 9 and maybe more.

**Describe alternatives you've considered**
geerlingguy

**Additional context**
The README should explain how to run the role multiple time with different vars.

**Comment by robertdebock** [comment]
Fair point, I think you'd like to see how to install multiple java versions. I'll work on it, thanks @bbaassssiiee

**Comment by bbaassssiiee** [comment]
Having multiple versions present and switching with **alternatives** is quite common.

**Comment by robertdebock** [comment]
I've changed the [documentation](https://github.com/robertdebock/ansible-role-java/blob/master/README.md) a bit. Please let me know if that's what you were expecting.
